DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS virtual_accounts;
DROP TABLE IF EXISTS product_categories;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS carts;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS transactions;