// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"time"
)

type Cart struct {
	ID         int64     `json:"id"`
	CustomerID int64     `json:"customer_id"`
	ProductID  int64     `json:"product_id"`
	Qty        int64     `json:"qty"`
	CreatedAt  time.Time `json:"created_at"`
}

type Customer struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Address   string    `json:"address"`
	CreatedAt time.Time `json:"created_at"`
}

type Order struct {
	ID         int64 `json:"id"`
	CustomerID int64 `json:"customer_id"`
	Amount     int64 `json:"amount"`
	// WAITING_PAYMENT/PAID/CANCEL
	Status           string    `json:"status"`
	VirtualAccountID int64     `json:"virtual_account_id"`
	IssuedAt         time.Time `json:"issued_at"`
	ExpiredAt        time.Time `json:"expired_at"`
	CreatedAt        time.Time `json:"created_at"`
}

type OrderItem struct {
	ID          int64     `json:"id"`
	CategoryID  int64     `json:"category_id"`
	Name        string    `json:"name"`
	ImageUrl    string    `json:"image_url"`
	Description string    `json:"description"`
	Price       int64     `json:"price"`
	Qty         int64     `json:"qty"`
	ProductID   int64     `json:"product_id"`
	OrderID     int64     `json:"order_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type OrderProof struct {
	ID             int64     `json:"id"`
	OrderID        int64     `json:"order_id"`
	NameHolder     string    `json:"name_holder"`
	RekeningNumber int64     `json:"rekening_number"`
	ImageUrl       string    `json:"image_url"`
	CreatedAt      time.Time `json:"created_at"`
}

type Product struct {
	ID          int64     `json:"id"`
	CategoryID  int64     `json:"category_id"`
	Name        string    `json:"name"`
	ImageUrl    string    `json:"image_url"`
	Description string    `json:"description"`
	Price       int64     `json:"price"`
	Qty         int64     `json:"qty"`
	CreatedAt   time.Time `json:"created_at"`
}

type ProductCategory struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Transaction struct {
	ID         int64 `json:"id"`
	CustomerID int64 `json:"customer_id"`
	// IN_DELIVERY/DELIVERED/SUCCESS
	Status    string    `json:"status"`
	IssuedAt  time.Time `json:"issued_at"`
	OrderID   int64     `json:"order_id"`
	CreatedAt time.Time `json:"created_at"`
}

type VirtualAccount struct {
	ID             int64     `json:"id"`
	Name           string    `json:"name"`
	Description    string    `json:"description"`
	RekeningNumber int64     `json:"rekening_number"`
	CreatedAt      time.Time `json:"created_at"`
}
